FROM node:alpine as builder 

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install -g npm@8.5.0
RUN npm install --save --legacy-peer-deps

COPY ./ ./

RUN npm run build

FROM nginx
EXPOSE 80

COPY --from=builder /usr/src/app/build /usr/share/nginx/html


