# FROM python:3.8.5-alpine 
FROM python:3.8.5

EXPOSE 9999

WORKDIR /usr/src/admin

COPY . .

RUN ["pip", "install", "--upgrade" ,"setuptools"]

RUN ["python", "-m", "pip", "install", "--upgrade" ,"pip"]

RUN ["pip", "install", "-r", "requirements.txt"]

CMD ["python3", "manage.py", "runserver", "0:9999"]